# fly.toml app configuration file generated for my-personal-website on 2025-07-09T00:01:51-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-personal-website'
primary_region = 'gru'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'my-personal-website.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  size = 'shared-cpu-1x'
  memory = "1gb"
