name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Elixir and OTP
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.4-otp-28'
          otp-version: '28'

      - name: Install dependencies
        working-directory: ./src
        run: mix deps.get

      - name: Compile
        working-directory: ./src
        run: mix compile

      - name: Fly Deploy
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          args: "deploy --remote-only"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
